export const uniList = [
  {
    domains: ["acms.edu.my"],
    web_pages: ["http://www.acms.edu.my/"],
    name: "Allianze College of Medical Sciences (ACMS)",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["aeu.edu.my"],
    web_pages: ["http://www.aeu.edu.my/"],
    name: "Asia E University",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["aimst.edu.my"],
    web_pages: ["http://www.aimst.edu.my/"],
    name: "Aimst University",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["aiu.edu.my"],
    web_pages: ["http://www.aiu.edu.my/"],
    name: "Al-Bukhari International University",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["apiit.edu.my"],
    web_pages: ["http://www.apiit.edu.my/"],
    name: "Asia Pacific Institute of Information Technology (APIIT)",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["atc2u.com"],
    web_pages: ["http://www.atc2u.com/"],
    name: "Advance Tertiary College",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["bac.edu.my"],
    web_pages: ["http://www.bac.edu.my/"],
    name: "Brickfields Asia College",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["binary.edu.my"],
    web_pages: ["http://www.binary.edu.my/"],
    name: "Binary University College of Managemant & Entrepreneurship",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["bmi.edu.my"],
    web_pages: ["http://www.bmi.edu.my/"],
    name: "British Malaysian Institute",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["city.edu.my"],
    web_pages: ["http://www.city.edu.my/"],
    name: "City University College of Science and Technology",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["curtin.edu.my"],
    web_pages: ["http://www.curtin.edu.my/"],
    name: "Curtin University of Technology, Sarawak Campus",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["cybermed.edu.my"],
    web_pages: ["http://www.cybermed.edu.my/"],
    name: "Cyberjaya University College of Medical Science",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ftmsglobal.com"],
    web_pages: ["http://www.ftmsglobal.com/"],
    name: "FTMS Global Academy",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["help.edu.my"],
    web_pages: ["http://www.help.edu.my/"],
    name: "Help University College",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["hikmah.edu.my"],
    web_pages: ["http://www.hikmah.edu.my/"],
    name: "Darul Hikmah Islamic College",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["i4p.edu.my"],
    web_pages: ["http://www.i4p.edu.my/"],
    name: "Institute of Teachers Education, Penang",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["iact.edu.my"],
    web_pages: ["http://www.iact.edu.my/"],
    name: "Iact College",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["iic.edu.my"],
    web_pages: ["http://www.iic.edu.my/"],
    name: "International Islamic College",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["iiu.edu.my"],
    web_pages: ["http://www.iiu.edu.my/"],
    name: "International Islamic University",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["imu.edu.my"],
    web_pages: ["http://www.imu.edu.my/"],
    name: "International Medical University",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["instedt.edu.my"],
    web_pages: ["http://www.instedt.edu.my/"],
    name: "Darul Takzim Institute of Technology",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipb.edu.my"],
    web_pages: ["http://www.ipb.edu.my/"],
    name: "Baitulmal Management Institute (IPB)",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipbl.edu.my"],
    web_pages: ["http://www.ipbl.edu.my/"],
    name: "Institute of Teachers Education, Batu Lintang",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipbmm.edu.my"],
    web_pages: ["http://www.ipbmm.edu.my/"],
    name: "Institute of Teachers Education, Malay Language",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipda.edu.my"],
    web_pages: ["http://www.ipda.edu.my/"],
    name: "Institute of Teachers Education, Darul Aman",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipgkkb.edu.my"],
    web_pages: ["http://www.ipgkkb.edu.my/"],
    name: "Institute of Teachers Education, Kota Bharu",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipgkrajang.edu.my"],
    web_pages: ["http://www.ipgkrajang.edu.my/"],
    name: "Institute of Teachers Education, Rajang",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipgkti.edu.my"],
    web_pages: ["http://www.ipgkti.edu.my/"],
    name: "Institute of Teachers Education, Temenggong Ibrahim",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipgmkdri.edu.my"],
    web_pages: ["http://www.ipgmkdri.edu.my/"],
    name: "Institute of Teachers Education, Dato' Razali Ismail",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipgmksm.edu.my"],
    web_pages: ["http://www.ipgmksm.edu.my/"],
    name: "Institute of Teachers Education, Sultan Mizan",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipgmtawau.edu.my"],
    web_pages: ["http://www.ipgmtawau.edu.my/"],
    name: "Institute of Teachers Education, Tawau",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipgperlis.edu.my"],
    web_pages: ["http://www.ipgperlis.edu.my/"],
    name: "Institute of Teachers Education, Perlis",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipik.edu.my"],
    web_pages: ["http://www.ipik.edu.my/"],
    name: "Institute of Teachers Education, Ilmu Khas",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipip.edu.my"],
    web_pages: ["http://www.ipip.edu.my/"],
    name: "Institute of Teachers Education, Ipoh",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipislam.edu.my"],
    web_pages: ["http://www.ipislam.edu.my/"],
    name: "Institute of Teachers Education, Islamic Education",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipkent.edu.my"],
    web_pages: ["http://www.ipkent.edu.my/"],
    name: "Institute of Teachers Education, Kent",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipks.edu.my"],
    web_pages: ["http://www.ipks.edu.my/"],
    name: "Institute of Teachers Education, Keningau",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ippm.edu.my"],
    web_pages: ["http://www.ippm.edu.my/"],
    name: "Institute of Teachers Education, Melaka",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["iprm.edu.my"],
    web_pages: ["http://www.iprm.edu.my/"],
    name: "Institute of Teachers Education, Raja Melewar",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipsah.edu.my"],
    web_pages: ["http://www.ipsah.edu.my/"],
    name: "Institute of Teachers Education, Sultan Abdul Halim",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipsmiri.edu.my"],
    web_pages: ["http://www.ipsmiri.edu.my/"],
    name: "Institute of Teachers Education, Sarawak",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["iptaa.edu.my"],
    web_pages: ["http://www.iptaa.edu.my/"],
    name: "Institute of Teachers Education, Tengku Ampuan Afzan",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["iptb.edu.my"],
    web_pages: ["http://www.iptb.edu.my/"],
    name: "Institute of Teachers Education, Tuanku Bainun",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["ipteknik.edu.my"],
    web_pages: ["http://www.ipteknik.edu.my/"],
    name: "Institute of Teachers Education, Technical Education",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["iptho.edu.my"],
    web_pages: ["http://www.iptho.edu.my/"],
    name: "Institute of Teachers Education, Tun Hussein Onn",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["iptips.edu.my"],
    web_pages: ["http://www.iptips.edu.my/"],
    name: "Perlis Islamic Higher Learning Institute",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["iucn.edu.my"],
    web_pages: ["http://www.iucn.edu.my/"],
    name: "International University College of Nursing (IUCN)",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["iuctt.edu.my"],
    web_pages: ["http://www.iuctt.edu.my/"],
    name: "International University College of Technology Twintech (IUCTT)",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["kbu.edu.my"],
    web_pages: ["http://www.kbu.edu.my/"],
    name: "KBU International College",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["kdu.edu.my"],
    web_pages: ["http://www.kdu.edu.my/"],
    name: "KDU College Sdn Bhd",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["kias.edu.my"],
    web_pages: ["http://www.kias.edu.my/"],
    name: "Sultan Ismail Petra International Islamic College",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["kidu-darululum.blogspot.com"],
    web_pages: ["http://kidu-darululum.blogspot.com/"],
    name: "Darul Ulum Islamic College",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
  {
    domains: ["kiperak.edu.my"],
    web_pages: ["http://www.kiperak.edu.my/"],
    name: "Perak Islamic College",
    alpha_two_code: "MY",
    "state-province": null,
    country: "Malaysia",
  },
];
